spring:
  datasource:
    url: ${DB_USER:jdbs:postgresql://localhost:5432/demobase}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL100Dialect
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}

#Aplication properties
app:
  jwt:
    secret: ${JWT_SECRET:Fx54Yey23Ur}
    expirationS: ${JWT_EXPIRATION_S:300}