spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/demobase}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}
  application:
    name: auth-api

server:
  port: ${PORT:8081}

#Aplication properties
app:
  jwt:
    secret: ${JWT_SECRET:Fx54Yey23Ur}
    expirationS: ${JWT_EXPIRATION_S:300}

ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    appname: auth-api
  client:
    fetchRegistry: true
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  host:
    connect-timeout-millis: 500000
    socket-timeout-millis: 500000
  ignored-services: "*"
  routes:
    beers-api:
      path: /beers-api/**
      url: http://localhost:8091/beers-api
      strip-prefix: true
    auth-api:
      path: /auth/**
      url: forward:/auth-api
      strip-prefix: true

hystrix:
  command:
    beers-api:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000
