spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/demobase}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}
  application:
    name: auth-api

server:
  port: ${PORT:8081}

#Aplication properties
app:
  jwt:
    secret: ${JWT_SECRET:Fx54Yey23Ur}
    expirationS: ${JWT_EXPIRATION_S:300}

eureka:
  instance:
    appname: auth-api
  client:
    fetchRegistry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka


zuul:
  routes:
    beers:
      path: /beer/**
      serviceId: beers-api
    #      url: http://localhost:8091/beers-api/v1/beers?beerName=Buzz
    auth:
      path: /auth/**
      url: forward:/
#      strip-prefix: true
#      serviceId: auth-api
#      url: http://localhost:8081/auth-api/v1/test/all
  host:
    socket-timeout-millis: 50000